config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root "static_pages#home"

  resources :funds do
    post "add_user", on: :collection
    resources :statements, expect: %i(destroy update)
  end
  resources :user_funds, expect: %i(destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :user_fund
  belongs_to :week
end

app/models/fund.rb
class Fund < ApplicationRecord

  FUND_PARAMS = [:name,
    :total_money,
    :founder_id,
    {user_funds_attributes: [
      {user_attributes: [:email, :skip_password_validation]},
      {histories_attributes: [:money, :status]},
      :founder,
      :user_id
    ]}
  ].freeze

  has_many :user_funds, dependent: :destroy
  has_many :users, through: :user_funds, dependent: :destroy

  accepts_nested_attributes_for :user_funds, reject_if: :duplicate, allow_destroy: true

  validates_presence_of :name

  scope :list, (lambda do
    select :id, :name, :total_money, :created_at, :updated_at
  end)

  def duplicate attr
    return false if user_funds.blank?
    return true if user_funds.last.user_id == attr[:user_id].to_i
  end
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user_fund
end

app/models/month.rb
class Month < ApplicationRecord
  has_many :weeks
end

app/models/statement.rb
class Statement < ApplicationRecord
  belongs_to :user_fund

  validates_presence_of :money, :stop_loss, :take_profit, :loss, :profit

  STATEMENT_PARAMS = [:money, :guess, :status, :stop_loss, :take_profit, :loss,
    :profit, :picture, :created_at, :updated_at].freeze

  scope :list, (lambda do
    select :id, :money , :guess, :status, :stop_loss, :take_profit, :loss, :profit,
      :picture, :created_at, :updated_at
  end)
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable
  has_many :user_funds, dependent: :destroy
  has_many :funds, through: :user_funds, dependent: :destroy
  has_one_attached :avatar
  before_save :avatar_nil


  before_create :set_password
  attr_accessor :skip_password_validation

  protected
  def password_required?
    return false if skip_password_validation
    super
  end

  private
  def set_password
    if skip_password_validation
      self.password = Devise.friendly_token.first(Settings.controller.funds_controller.random_pw)
      self.password_confirmation = password
    end
  end

  def avatar_nil
    return if avatar.attached?
    avatar.attach(io: File.open("#{Rails.root}/vendor/assets/images/profile.jpg"), filename: "profile.jpg", content_type: "image/jpeg")
  end
end

app/models/user_fund.rb
class UserFund < ApplicationRecord
  has_many :histories, dependent: :destroy
  has_many :statements, dependent: :destroy
  has_many :days, dependent: :destroy
  has_many :members, class_name: "UserFund", foreign_key: "founder_id"
  belongs_to :user
  belongs_to :fund
  belongs_to :manager, class_name: "UserFund", optional: true, foreign_key: "founder_id"

  accepts_nested_attributes_for :user, reject_if: :all_blank
  accepts_nested_attributes_for :histories, reject_if: :all_blank

  before_update :update_founder, if: [:founder, :founder_id]
  after_commit :add_members, if: :founder, unless: :founder_id

  delegate :user, to: :manager, prefix: :founder

  scope :fund_index, ->(user_id) {where(user_id: user_id).includes({manager: :user}, :fund, :user)}

  def set_founder
    update founder: true, founder_id: nil
  end

  private
  def update_founder
    self.founder = false unless id == founder_id
  end

  def add_members
    members << fund.user_funds
  end
end

app/models/week.rb
class Week < ApplicationRecord
  has_many :days
  belongs_to :month
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  protect_from_forgery with: :exception
  before_action :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  protected

  def configure_permitted_parameters
    added_attrs = %i(name avatar mobile_number address facebook).freeze
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/funds_controller.rb
  class FundsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_fund, except: %i(new create index add_user)

  def index
    @pagy, @fund_details = pagy UserFund.fund_index(current_user.id),
      items: Settings.controller.funds_controller.page
  end

  def show; end

  def new
    @fund = Fund.new
    @user = current_user.decorate
    @key = SecureRandom.random_number Settings.random_key
  end

  def create
    @fund = Fund.new fund_params
    if @fund.save
      flash[:success] = t(".created")
      redirect_to funds_path
    else
      flash[:error] = t(".create_unsuccess")
      @user = current_user.decorate
      @key = SecureRandom.random_number Settings.random_key
      render :new
    end
  end

  def edit; end

  def update
    @fund.update name: fund_params[:name]
    if @user_fund = UserFund.find_by(id: fund_params[:founder_id])
      @user_fund.set_founder
    end
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @fund.destroy
    respond_to do |format|
      format.js
    end
  end

  def add_user
    unless @user = User.find_by(email: params[:email])
      @user = User.new email: params[:email]
    end
    @history = History.new money: params[:money]
    @key = SecureRandom.random_number Settings.random_key
    respond_to do |format|
      format.js
    end
  end

  private
  def fund_params
    params.require(:fund).permit Fund::FUND_PARAMS
  end

  def load_fund
    return if @fund = Fund.find_by(id: params[:id])
    flash[:error] = t(".you_not_permited")
    redirect_to root_path
  end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_user_fund
  before_action :load_statement, except: %i(index new create)

  def index
    @pagy_statement, @statements = pagy Statement.list, items: Settings.controller.statements_controller.page
    @statements = StatementDecorator.decorate_collection @statements
  end

  def show; end

  def new
    @statement = @user_fund.statements.new
  end

  def create
    @statement = @user_fund.statements.new statement_params
    if @statement.save
      flash[:success] = t(".created")
      redirect_to fund_statements_path
    else
      flash[:error] = t(".create_unsuccess")
      render :new
    end
  end

  def edit; end

  private

  def load_user_fund
    return if @user_fund = UserFund.find_by(user_id: current_user.id, fund_id: params[:fund_id])
    flash[:error] = t(".user_fund_not_found")
    redirect_to user_funds_path
  end

  def load_statement
    return if @statement = @user_fund.statements.find_by(id: params[:id]).decorate
    flash[:error] = t(".statement_not_found")
    redirect_to fund_statements_path
  end

  def statement_params
    params.require(:statement).permit Statement::STATEMENT_PARAMS
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout "application", only: %i(edit update)
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/funds/_edit_modal.html.erb
<div class="modal fade" id=<%= "edit_form#{fund.id}" %> tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t ".edit_fund" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with model: fund do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :name, t(".name") %>
            <%= f.text_field :name, class: "form-control", placeholder: t(".enter_name") %>
          </div>
          <div class="form-group">
            <%= f.label :founder, t(".founder") %>
            <%= f.select "founder_id", fund.user_funds.collect {|p| [ p.user.name, p.id ]}, {}, class: "js-example-basic-single", style: "width:100%" %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.button t(".save"), class: "btn btn-success" %>
          <button type="button" class="btn btn-light" data-dismiss="modal"><%= t ".form_cancel" %></button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/funds/_form.html.erb
<%= form_for @fund do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="modal-body">
    <div class="form-group">
      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control", placeholder: t(".enter_name") %>
    </div>
    <div class="form-group">
      <%= f.label :total_money, t(".total_money") %>
      <%= f.text_field :total_money, class: "total_money form-control", placeholder:
        t(".enter_total_money"), readonly: true %>
    </div>
  </div>
  <hr>
  <div class="modal-body">
    <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#user_form" data-whatever="@mdo">
      <i class="mdi mdi-account-plus"></i><%= t ".add_user" %></button>
    <table class="table">
      <thead>
        <tr>
          <th><%= t ".user_email" %></th>
          <th><%= t ".money" %></th>
          <th><%= t ".status" %></th>
          <th><%= t ".role" %></th>
          <th><%= t ".action" %></th>
        </tr>
      </thead>
      <tbody id="users">
        <tr>
          <%= fields_for "fund[user_funds_attributes][#{@key}]" do |uf| %>
            <%= uf.hidden_field :user_id, value: @user.id %>
            <%= uf.fields_for "user_attributes" do |u| %>
              <td>
                <div class="form-control" readonly><%= @user.email %></div>
              </td>
            <% end %>
            <%= uf.fields_for "histories_attributes[#{@key}]" do |h| %>
              <td>
                <div class="input-group">
                  <%= h.number_field :money, value: Settings.views.funds.form.default_money,
                    class: "money form-control" %>
                  <div class="input-group-append">
                    <span class="input-group-text">USD</span>
                  </div>
                </div>
                <%= h.hidden_field :status, value: true %>
              </td>
            <% end %>
            <td><%= label_tag @user.user_badge[:name], nil, class: @user.user_badge[:class] %></td>
            <td><%= uf.hidden_field :founder, value: true %><i class="mdi mdi-crown text-warning"></i></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="modal-footer">
    <%= f.button yield(:button_text), class: "btn btn-success" %>
    <button type="button" class="btn btn-light" data-dismiss="modal"><%= t ".form_cancel" %></button>
  </div>
<% end %>
<%= render "modal" %>

app/views/funds/_fund_detail.html.erb
<tr id=<%= fund_detail.fund_id %> >
  <td class="fund_name"><%= fund_detail.fund.name %></td>
  <td><%= fund_detail.fund.total_money %></td>
  <td class="founder_name"><%= fund_detail.founder_user.name %></td>
  <td>
    <%= link_to fund_path(fund_detail.fund_id) do %><i class="mdi mdi-eye text-success"></i><% end %>
    <%= link_to fund_path(fund_detail.fund_id), data: {toggle: "modal", target: "#edit_form#{fund_detail.fund_id}", whatever: "@mdo"} do %><i class="mdi mdi-table-edit text-primary"></i><% end %>
    <%= link_to fund_path(fund_detail.fund_id), remote: true, method: :delete, data: {confirm_swal: "Are you sure?"} do %>
      <i class="mdi mdi-delete text-danger"></i><% end %>
  </td>
  <%= render "edit_modal", fund: fund_detail.fund %>
</tr>

app/views/funds/_modal.html.erb
<div class="modal fade" id="user_form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t ".add_user" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with url: add_user_funds_path, id: "add_user" do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :email, t(".email") %>
            <%= f.text_field :email, class: "form-control", placeholder: t(".enter_email") %>
          </div>
          <div class="form-group">
            <%= f.label :money, t(".money") %>
            <div class="input-group">
              <%= f.number_field :money, class: "form-control", placeholder:
              t(".enter_money") %>
              <div class="input-group-append">
                <span class="input-group-text">USD</span>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.button t(".add"), class: "btn btn-success" %>
          <button type="button" class="btn btn-light" data-dismiss="modal" onclick="clearUser()"><%= t ".form_cancel" %></button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/funds/_user_fund_fields.html.erb
<tr>
  <%= fields_for "fund[user_funds_attributes][#{data[:key]}]" do |uf| %>
    <% if data[:u].id %>
      <%= uf.hidden_field :user_id, value: data[:u].id %>
    <% end %>
    <%= uf.fields_for "user_attributes" do |u| %>
      <td>
        <div class="form-control" readonly><%= data[:u].email %></div>
        <% unless data[:u].id %>
          <%= u.hidden_field :email, value: data[:u].email %>
          <%= u.hidden_field :skip_password_validation, value: true %>
        <% end %>
      </td>
    <% end %>
    <%= uf.fields_for "histories_attributes[#{data[:key]}]" do |h| %>
      <td>
        <div class="input-group">
          <%= h.number_field :money, value: data[:h].money, class: "money form-control"  %>
          <div class="input-group-append">
            <span class="input-group-text">USD</span>
          </div>
        </div>
        <%= h.hidden_field :status, value: true %>
      </td>
    <% end %>
    <td><%= label_tag data[:u].decorate.user_badge[:name], nil, class: data[:u].decorate.user_badge[:class] %></td>
    <td><i class="mdi mdi-worker text-info"></i></td>
  <% end %>
  <td><a href="#" onclick="$(this).closest('tr').remove()">
    <i class="mdi mdi-delete text-danger"></i></a>
  </td>
</tr>

app/views/funds/add_user.js.erb
$('<%= escape_javascript(render "funds/user_fund_fields", data: {key: @key, u: @user, h: @history}) %>')
  .appendTo('#users');

app/views/funds/destroy.js.erb
<% if @fund.errors.empty? %>
  $('<%= "##{@fund.id}" %>').remove();
  swal({
    title: 'Congratulations!',
    text: 'You delete fund success',
    icon: 'success',
    button: {
      text: "Continue",
      value: true,
      visible: true,
      className: "btn btn-primary"
    }
  })
<% else %>
  swal({
    title: 'Read the alert!',
    text: <% object.errors.full_messages.each do |msg| %><%= msg %><% end %>,
    button: {
      text: "OK",
      value: true,
      visible: true,
      className: "btn btn-primary"
    }
  })
<% end %>

app/views/funds/edit.html.erb
<%= provide :title, t(".edit_fund") %>
<%= provide :button_text, t(".submit") %>

<div class="row flex-grow">
  <div class="col-8">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= t ".add_new_fund"%></h4>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/funds/index.html.erb
<%= provide :title, t(".funds") %>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= t ".funds" %></h4>
        <table class="table">
          <thead>
            <tr>
              <th><%= t ".fund_name" %></th>
              <th><%= t ".total_money" %></th>
              <th><%= t ".founder" %></th>
              <th><%= t ".action" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "fund_detail", collection: @fund_details %>
          </tbody>
        </table>
        <%= pagy_bootstrap_nav(@pagy).html_safe %>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag "fund" %>

app/views/funds/new.html.erb
<%= provide :title, t(".create_fund") %>
<%= provide :button_text, t(".submit") %>

<div class="row flex-grow">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= t ".add_new_fund"%></h4>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "fund" %>

app/views/funds/show.html.erb
<%= provide :title, @fund.name %>

<div class="row">
  <div class="col-12 card">
    <div class="card-body">
      <address>
        <p class="font-weight-bold"><%= @fund.name %></p>
          $ <%= @fund.total_money %>
        <p><%= t ".created_at" %>: <%= l @fund.created_at, format: :full %></p>
        <p><%= t ".updated_at" %>: <%= l @fund.updated_at, format: :full %></p>
      </address>
      <%= link_to t(".edit_but"), edit_fund_path(@fund), class: "btn btn-primary btn-sm float-right" %>
    </div>
  </div>
</div>

app/views/funds/update.js.erb
<% if @fund.errors.empty? %>
  $('<%= "##{@fund.id}" %>').children('.fund_name').html('<%= @fund.name %>');
  $('<%= "##{@fund.id}" %>').children('.founder_name').html('<%= @user_fund.user.name %>');

  swal({
    title: 'Congratulations!',
    text: 'You delete fund success',
    icon: 'success',
    button: {
      text: "Continue",
      value: true,
      visible: true,
      className: "btn btn-primary"
    }
  })
<% else %>
  swal({
    title: 'Read the alert!',
    text: <% object.errors.full_messages.each do |msg| %><%= msg %><% end %>,
    button: {
      text: "OK",
      value: true,
      visible: true,
      className: "btn btn-primary"
    }
  })
<% end %>

app/views/layouts/_alert.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    $(document).ready(function() {
      <% flash.each do |f| %>
        <% type = f[0].to_s.gsub("alert", "error").gsub("notice", "info") %>
        showFlash("<%= type %>", "<%= f[1] %>")
      <% end %>
    })
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container-fluid clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018 <a href="#">Bootstrapdash</a>. All rights reserved.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
  </div>
</footer>

app/views/layouts/_meta.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

app/views/layouts/_navbar.html.erb
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <%= link_to root_path, class: "navbar-brand brand-logo" do %>
      <%= image_tag "logo.svg", alt: "logo" %>
    <% end %>
    <%= link_to root_path, class: "navbar-brand brand-logo-mini" do %>
      <%= image_tag "logo-mini.svg", alt: "logo" %>
    <% end %>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center mr-2" type="button" data-toggle="minimize">
      <i class="mdi mdi-menu"></i>
    </button>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <%= link_to "#", class: "nav-link count-indicator dropdown-toggle", id: "notificationDropdown", data: {toggle: "dropdown"} do %>
          <i class="mdi mdi-bell-outline"></i>
          <span class="count bg-success"><%= t ".number_bell" %></span>
        <% end %>
        <div class="dropdown-menu navbar-dropdown navbar-dropdown-large preview-list" aria-labelledby="notificationDropdown">
          <h6 class="p-3 mb-0 text-center">Notifications</h6>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
                <%= image_tag "faces/face4.jpg", class: "profile-pic" %>
            </div>
            <div class="preview-item-content">
              <p class="mb-0">Dany Miles <span class="text-small text-muted">commented on your photo</span></p>
            </div>
          </a>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
                <%= image_tag "faces/face3.jpg", class: "profile-pic" %>
            </div>
            <div class="preview-item-content">
              <p class="mb-0">James <span class="text-small text-muted">posted a photo on your wall</span></p>
            </div>
          </a>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
                <%= image_tag "faces/face2.jpg", class: "profile-pic" %>
            </div>
            <div class="preview-item-content">
              <p class="mb-0">Alex <span class="text-small text-muted">just mentioned you in his post</span></p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <p class="p-3 mb-0 text-center">View all activities</p>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown">
          <i class="mdi mdi-email-outline"></i>
          <span class="count bg-warning">5</span>
        </a>
        <div class="dropdown-menu navbar-dropdown navbar-dropdown-large preview-list" aria-labelledby="messageDropdown">
          <h6 class="p-3 mb-0 text-center">Messages</h6>
          <a class="dropdown-item preview-item">
            <div class="preview-item-content flex-grow">
              <span class="badge badge-pill badge-success">Request</span>
              <p class="text-small text-muted ellipsis mb-0">
                Suport needed for user123
              </p>
            </div>
            <p class="text-small text-muted align-self-start">4:10 PM</p>
          </a>
          <a class="dropdown-item preview-item">
            <div class="preview-item-content flex-grow">
              <span class="badge badge-pill badge-warning">Invoices</span>
              <p class="text-small text-muted ellipsis mb-0">
                Invoice for order is mailed
              </p>
            </div>
            <p class="text-small text-muted align-self-start">4:10 PM</p>
          </a>
          <a class="dropdown-item preview-item">
            <div class="preview-item-content flex-grow">
              <span class="badge badge-pill badge-danger">Projects</span>
              <p class="text-small text-muted ellipsis mb-0">
                New project will start tomorrow
              </p>
            </div>
            <p class="text-small text-muted align-self-start">4:10 PM</p>
          </a>
          <h6 class="p-3 mb-0 text-center">See all activity</h6>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right ml-lg-auto">
      <li class="nav-item nav-search">
        <form class="nav-link form-inline mt-2 mt-md-0 d-none d-lg-flex">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search">
            <div class="input-group-append">
              <span class="input-group-text">
                <i class="mdi mdi-magnify"></i>
              </span>
            </div>
          </div>
        </form>
      </li>
      <li class="nav-item dropdown d-none d-lg-flex">
        <a class="nav-link dropdown-toggle" id="languageDropdown" href="#" data-toggle="dropdown">
          <i class="mdi mdi-earth"></i>
          English
        </a>
        <div class="dropdown-menu navbar-dropdown" aria-labelledby="languageDropdown">
          <a class="dropdown-item" href="#">
            French
          </a>
          <a class="dropdown-item" href="#">
            Spain
          </a>
          <a class="dropdown-item" href="#">
            Latin
          </a>
          <a class="dropdown-item" href="#">
            Japanese
          </a>
        </div>
      </li>
      <li class="nav-item  nav-profile dropdown">
        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown">
            <%= image_tag current_user.avatar.variant(resize: "30x30"), class: "rounded-circle" %>
          <% if current_user.name.present? %>
            <span class="profile-name"><%= current_user.name %></span>
          <% else %>
            <span class="profile-name"><%= t ".no_name" %></span>
          <% end %>
        </a>
        <div class="dropdown-menu navbar-dropdown w-100" aria-labelledby="profileDropdown">
          <%= link_to edit_user_registration_path, class: "dropdown-item" do%>
            <i class="mdi mdi-account-box mr-2 text-success"></i>
            <%= t ".profile" %>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do%>
            <i class="mdi mdi-logout mr-2 text-primary"></i>
            <%= t ".signout" %>
          <% end %>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="mdi mdi-menu"></span>
    </button>
  </div>
</nav>

app/views/layouts/_settings-panel.html.erb
<div class="theme-setting-wrapper">
  <div id="settings-trigger"><i class="mdi mdi-settings"></i></div>
  <div id="theme-settings" class="settings-panel">
    <i class="settings-close mdi mdi-close"></i>
    <p class="settings-heading">SIDEBAR SKINS</p>
    <div class="sidebar-bg-options" id="sidebar-light-theme"><div class="img-ss rounded-circle bg-light border mr-3"></div>Light</div>
    <div class="sidebar-bg-options selected" id="sidebar-dark-theme"><div class="img-ss rounded-circle bg-dark border mr-3"></div>Dark</div>
    <p class="settings-heading mt-2">HEADER SKINS</p>
    <div class="color-tiles mx-0 px-4">
      <div class="tiles primary"></div>
      <div class="tiles success"></div>
      <div class="tiles warning"></div>
      <div class="tiles danger"></div>
      <div class="tiles pink"></div>
      <div class="tiles info"></div>
      <div class="tiles dark"></div>
      <div class="tiles default"></div>
    </div>
  </div>
</div>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/meta" %>
    <title>CapitalizeManagement</title>
    <%= stylesheet_pack_tag "application" %>
    <%= javascript_pack_tag "application" %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= yield %>
    <%= render "layouts/alert" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <script type="text/javascript">
    <% object.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>');
    <% end %>
  </script>
<% end %>